#!/usr/bin/env bash
# Create PID file

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo $$ > /var/run/myscript.pid

# Trap signals
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
