#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS=: read -r username _ uid _ home _; do
    echo "$username"
    echo "$uid"
    echo "$home"
done < /etc/passwd
