#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=: read -r username _ uid _ home _; do
    echo "The user $username is part of the GROUP_ID gang, lives in $home and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < /etc/passwd
