#!/usr/bin/env bash
# ls using for loop

for file in *
do
    if [ ! -f "$file" ] || [[ "$file" == .* ]]
    then
        continue
    fi

    filename=$(basename -- "$file")
    extension="${filename##*.}"
    filename="${filename%.*}"

    if [[ $filename == *-* ]]
    then
        filename="${filename#*-}"
    fi

    printf "%s\n" "$filename"
done
