#!/usr/bin/env bash
#create RSA key pair
ssh-keygen -t rsa -b 4096 -f school -N betty

# Configure SSH client
echo "IdentityFile ~/.ssh/school" >> ~/.ssh/config
echo "PasswordAuthentication no" >> ~/.ssh/config

